name: "Fivemanage Lite"

services:
  database:
    image: mysql:8
    container_name: lite_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fivemanage-lite-dev
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql_data:/var/lib/mysql
